default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  enconding: utf8

development:
  <<: *default
  database: meetboard_dev

test:
  <<: *default
  database: meetboard_test

production:
  <<: *default
  database: meetboard_prod
